### ISSUE TITLE
Setting Metadata / Title

### ISSUE THREAD

**Issue by bryan** [iaincollins/nextjs-starter#1]
Thanks for the quick overview on how next.js 2.0 works together with the server with this starter repo. 

I was just playing around with it and couldn't get it to work with react-helmet on the server.js and was wondering if it was possible with the current configuration. Any input would be great - since I'm still learning how next works, thanks!

**Edit**: I suppose that I can add the 'next/head' and mess with it in the `<Head></Head>`, but is there a more native solution to add react-helmet?

**Comment by iaincollins** [comment]
Hi @bryan I'm haven't used react-helmet, but yes I'd lean to using next/head probably as it's part of Next.js already and means not having to add add another dependency (with example usage in [pages/page-specifc.js](https://github.com/iaincollins/nextjs-starter/blob/master/pages/page-specific.js).

It looks like it does the same sort of thing, and personally from the look of the docs I think I like the look of how next/head works more but I can see the case for using something might be found more commonly used elsewhere.

I'm not actually sure why react-helmet wouldn't work though, I wonder if that's why there is a next/head, or if it's that it's conflicting with next/head? So far all other React libs have worked out of the box for me with Next.js (touch wood).

**Comment by iaincollins** [comment]
I'd add that while I _think_ next/head currently covers things for headers pretty well, I'm in principle totally happy to add other examples with common React compatible libs!

**Comment by bryan** [comment]
Right. I think I'll stick with the native solution of `import next/head`since it does add another dependency. The reason I asked was because I'm currently porting an existing project over to next so I thought it might've been easier.

Thanks for the help!
