### ISSUE TITLE
Update to next.js 9?

### ISSUE THREAD

**Issue by luluhoc** [iaincollins/nextjs-starter#110]
Hey,

Are you planning on updating it to next.js 9?

**Comment by clipvui2512** [comment]
this project dead....

**Comment by luluhoc** [comment]
Shame

**Comment by iaincollins** [comment]
Hi there! 

Happy to say (belatedly) that project isn't dead but it got parked for a while due to some major changes in Next.js in v8 and with changes I knew were coming in 9.0 didn't want to do make the effort to update redundant.

Next.js 9.1 is amazing I hope to update this project soon, with the latest CSS and API examples!
