### ISSUE TITLE
Separate authentication server

### ISSUE THREAD

**Issue by sedubois** [iaincollins/nextjs-starter#26]
Hi and thanks again for this helpful project 🙂

Currently the authentication API is mixed with the next.js frontend server. For a production app these would need to be separated. Do you plan to do that?

**Comment by iaincollins** [comment]
This is a good question, and I've thought about but I think probably not.

The reason being is you need to have some session logic in your app end if you want to do Universal rendering (i.e. the server has got to be able to read an HTTP accessible cookie, get information about you from somewhere and rendering templates accordingly). 

The fact that it needs to use an HTTP cookie (because there is literally no other way to do it) is a pretty big deal; as your options are then narrowed to one of the following:

1. Create a more "lightweight" front end that uses it's own cookie tied to the session cookie of the auth platform, using a callback from the auth layer - a bit like how oAuth or other SSO platforms work. Of this introduces a bunch complexity and error cases that need to be catered for, like mismatching or stale tokens. Overall this could be quite a bit more code and introduces more error cases to handle.

2. Just leave the auth layer in the front end.

3. Of course, you don't care about supporting Universal rendering and just want to do client side only auth, then actually auth is pretty easy in any case.

In most cases No. 2 isn't actually a problem, as there is still no per-instance *state* in the server - the sessions can still be stored in any DB instance somewhere (in memory or in any other storage adapter supported by Express sessions), so there are no scalability bottlenecks inherit in it.

Normal web based production applications in other languages make no attempt to separate authentication out and they are just fine. While having a separate API layer is desirable - as it separates concerns and makes scaling services and teams easier, that's still possible with this authentication model.

I'll probably focus on taking the project in a direction of an easy to get running with practical example, maybe adding Bootstrap and some better examples of CSS, dynamic components etc. and improved documentation and error handling.

**Comment by iaincollins** [comment]
Closing this for now, but it's a good issue and welcome any future discussion on this thread!

Especially if someone has an idea about a good design for a better solution for auth (even if it ends up being a separate project).
