### ISSUE TITLE
Question: Session storage on server/client

### ISSUE THREAD

**Issue by davidrossjones** [iaincollins/nextjs-starter#35]
Firstly, thank you for a great starter project!

With your Session.js component implementation the current session is either retrieved from the server (via req) or the client (via localStorage).

How are these two kept in sync? For example I believe if there is a valid session on the server and localStorage is empty, an XHR request is made to the server to get the session (and set localStorage). However what happens if the server session is lost (deleted cookies etc) but localStorage still exists? 

The initial page load would show an empty session (not logged in via req) but client side routing will show as a valid session being present (logged in via localStorage).

It this scenario unlikely and not to be concerned about?

**Comment by iaincollins** [comment]
Sorry for taking a few days to getting round to answering.

Good question! This isn't very well explained outside of the code comments.

So, there is a normal expiry session time (`maxAge`) option in [./routes/auth.js](https://github.com/iaincollins/nextjs-starter/blob/master/routes/auth.js) but there is *also* a seperate but similarly named `clientMaxAge` option which I created to address the issue of them getting out of sync.

This is the inline documentation:

```javascript
    // How often the client should revalidate the session in ms (default 60s)
    // Does not impact the session life on the server, but causes the client to
    // always refetch session info after N seconds has elapsed since last
    // checked. Sensible values are between 0 (always check the server) and a
    // few minutes.
    clientMaxAge = 60000,
```

The `session.js` component on the client always does a get request to `/auth/session` to check the session is still valid every `clientMaxAge` seconds, so after 60 seconds the next page load triggered hits the server and it will update the session (and show you as logged out if the session is gone).

If you want to you can set `clientMaxAge` to `0` milliseconds and all that means is every time you load a new page it will check your session, that way you can never be out of sync - but pages will, possibly imperceptibly, load a little slower, especially on bad connections, just because it's hitting the server before rendering every page.

A short timeout of 60 seconds is an attempt at a compromise, especially as it doesn't happen very often that sessions on a server are deleted without the user logging out. You could even make it longer if you wanted (it's so rare that even 5 minutes or longer might be fine, depending on your site).

Improvements could be:

* The session could be checked in the background with `setInterval()`, instead of on page load.
* Server Side Events could be fired from the server when a session is logged out to inform any clients connected (although clients not connected to the server would not see it and would still need to be catered for).

**Comment by iaincollins** [comment]
I think this is hopefully a complete answer that is a good reference for folks in future.
