### ISSUE TITLE
iOS Safari "XMLHttpRequest failed: Unable to get session"

### ISSUE THREAD

**Issue by kuma-guy** [iaincollins/nextjs-starter#37]
Sometimes I got  "XMLHttpRequest failed: Unable to get session" when I back and forth super fast between pages using browser buttons but only occurs on iOS Safari

**Comment by kuma-guy** [comment]
<img width="665" alt="2017-07-15 11 19 05" src="https://user-images.githubusercontent.com/7978290/28235751-85f854c2-694f-11e7-82db-5152263be788.png">

**Comment by iaincollins** [comment]
Thanks for reporting this, that's interesting. I was looking at refactoring that code.

I'll improve the debugging at least so we can see if it's important or not (e.g. if it's just the XMLHttpRequest just be cancelled by the browser due to navigation that's fine as the session would still be valid).

**Comment by iaincollins** [comment]
Thanks for the bug report. I haven't been able to resolve this or replicate it so going to be lazy and just close this off as unless I'm bugged more about it or run into it a bunch myself I'm probably going to gloss over it.

I'm sure it's a real issue, but I don't have any thoughts on what to do about it and am vaguely hoping it just goes away over time (either in an Safari update, a Next.js update or due to refactoring).

If this makes anyone mad and they are still seeing it bug me to reopen and investigate it. Any additional specific info you can give to help replicate is always helpful.
