### ISSUE TITLE
Documentation on Authentication Setup / Email Setup?

### ISSUE THREAD

**Issue by zocheyado** [iaincollins/nextjs-starter#73]
I cannot seem to find any documentation on how to actually setup the authentication or the email setup. I have filled in the appropriate .env files but I cannot seem to figure out how to get this project to associated my MongoDB  with users, or where a model would be to map this information. I filled out the config in the docs and if I try and signup it says it will send an email, however since this does not happen out of the box I assume you have to config sendgrid or some other service that will actually do that. Because of that I cannot login and thus cannot test authentication. I understand I do not know everything about how this works which is why I am hoping for some documentation.

**Comment by iaincollins** [comment]
There is a working project in the examples folder, with an example .env file and it's own README.md that describes it and how to use. There is a step by step guide in the AUTHENTICATION.md on how to set up oAuth access with common providers.

There is also a more complex real-world example linked to from the root README.md (and NPM page) with a starter project if that helps (though it sounds like that might complicate things for you)  https://nextjs-starter.now.sh 

It will send an email from localhost if you do not configure an email account, but if your local network (internet provider or office lan) block email traffic, or if your email address provider blocks it (e.g. because it was sent from localhost - which some do) then you will never see it.

Given a username, password and mail server (host/port) it should work with any mail service (Google Mail, SendGrid, MailGun, etc).

Note that if you use a service like Google you might have explicitly enable SMTP email as it may only do webmail by default (this can depend on how and when your account was set up and/or if you have two factor authentication enabled).

The project doesn't actually send email, it just shows how to use nodemailer to avoid having any email sending specific logic in it, so I would try to figure that out separately if you are having problems with email.

The default example also logs the URL it emails and displays it on the console if you just want to test the URLs and can't send email from your local machine. Some internet providers block all email on their network that doesn't go through their servers, so this is a useful.

Tip: If the Next.js example app is clearing the console while running you can do something like `npm run dev > /tmp/debug.log | tail -f /tmp/debug.log` to avoid that.

If you don't specify a MONGO_URI  for the example project it will use an in memory database. If you do specify a MONGO_URI it will create a `users` collection and a `sessions` collection by default and populate them for you.

All you need to do is provide the connection string (e.g. by setting it in a .env) and it will 'just work' (at least for email). You don't need to specify a model anywhere if just using Mongo DB. You can use a local instance of MongoDB or a free test database from a service like mLab.

**Comment by zocheyado** [comment]
Thank you for all the info! I will check out those examples. So I have already setup a MONGO_URI (the one with the link to the DB, username and password in the URI.) So in theory I should be able to create an account via that (once the email portion is setup and working) and it will handle all of the collections and sessions for me automagically ?

**Comment by iaincollins** [comment]
PS: Have just updated my comment to be more useful as I mistakenly thought this was logged against NextAuth (the authentication library this uses, which was split off into it's own codebase recently).

**Comment by iaincollins** [comment]
Yes it should all just work if you give it a MONGO_URI (username and password, host, port and database name). You will need to create a database, but not the collections inside it (but it doesn't mind if there are collections in it already).

It can help to first connect to the database with a client like 'MongoHub' or 'Robo 3T' to see when it creates collections and users and to debug things (do the connection details work, does it create the collections, etc).

The schema is something like this:

```
{
  _id          : ObjectId,
  name         : String,
  email        : String,
  admin        : Boolean,
  // Properties emailToken and emailVerified are required for email auth.
  emailToken   : String,
  emailVerified: Boolean,
  // If using oAuth be sure to add add an Object for each oAuth provider.
  // These should match the provider name in lower case e.g. 'Google'->'google'
  // These will be used to store { id, accessToken, refreshToken } if provided.
  facebook     : Object,
  google       : Object,
  twitter      : Object
}
```

Users are created dynamically (this isn't ideal, but will updated whenever NextAuth 2.0 gets released).

**Comment by zocheyado** [comment]
Awesome thanks for the help, I will do a deep dive into this project tonight and I wanted to get those questions answered asap so I could really go hard. Thanks alot !

**Comment by iaincollins** [comment]
Closing this now but feel free to open a new issue or leave comments on this if you have any follow up questions.
